### ISSUE TITLE
AttributeError: 'RequirementDNode' object has no attribute 'id'

### ISSUE THREAD

**Issue by wentasah** [florath/rmtoo#1]
Hi, I've just discovered rmtoo. It seems to be a great tool. When I try current master I get the following error:
```
Traceback (most recent call last):
  File "./bin/rmtoo", line 14, in <module>
    main(sys.argv[1:], sys.stdout, sys.stderr)
  File "/home/wsh/src/rmtoo/rmtoo/lib/RmtooMain.py", line 76, in main
    exitfun(not main_func(args, mstdout, mstderr))
  File "/home/wsh/src/rmtoo/rmtoo/lib/RmtooMain.py", line 70, in main_impl
    return execute_cmds(config, input_mods, mstdout, mstderr)
  File "/home/wsh/src/rmtoo/rmtoo/lib/RmtooMain.py", line 49, in execute_cmds
    Output.execute(config, topic_continuum_set, mstderr, "cmad_")
  File "/home/wsh/src/rmtoo/rmtoo/lib/Output.py", line 91, in execute
    return topic_continuum_set.execute(output, func_prefix)
  File "/home/wsh/src/rmtoo/rmtoo/lib/TopicContinuumSet.py", line 62, in execute
    continuum.execute(executor, func_prefix)
  File "/home/wsh/src/rmtoo/rmtoo/lib/TopicContinuum.py", line 100, in execute
    FuncCall.pcall(executor, func_prefix + "topic_continuum_pre", self)
  File "/home/wsh/src/rmtoo/rmtoo/lib/FuncCall.py", line 28, in pcall
    return getattr(obj, method_name)(*args)
  File "/home/wsh/src/rmtoo/rmtoo/lib/Output.py", line 82, in cmad_topic_continuum_pre
    return self.__common_topic_continuum_pre(topic_continuum, "cmad_")
  File "/home/wsh/src/rmtoo/rmtoo/lib/Output.py", line 59, in __common_topic_continuum_pre
    topic_continuum.execute(output_obj, special)
  File "/home/wsh/src/rmtoo/rmtoo/lib/TopicContinuum.py", line 104, in execute
    topic_set.execute(executor, func_prefix)
  File "/home/wsh/src/rmtoo/rmtoo/lib/TopicSetWCI.py", line 41, in execute
    self.__topic_set.execute(executor, func_prefix)
  File "/home/wsh/src/rmtoo/rmtoo/lib/TopicSet.py", line 116, in execute
    self.__topic.execute(executor, func_prefix)
  File "/home/wsh/src/rmtoo/rmtoo/lib/Topic.py", line 105, in execute
    self.__requirements.execute(executor, func_prefix)
  File "/home/wsh/src/rmtoo/rmtoo/lib/RequirementSet.py", line 368, in execute
    self._named_nodes.values()):
  File "/home/wsh/src/rmtoo/rmtoo/outputs/csv1.py", line 50, in requirement_set_sort
    return sorted(list_to_sort, key=lambda r: r.id)
  File "/home/wsh/src/rmtoo/rmtoo/outputs/csv1.py", line 50, in <lambda>
    return sorted(list_to_sort, key=lambda r: r.id)
AttributeError: 'RequirementDNode' object has no attribute 'id'
Makefile:29: recipe for target 'artifacts/.rmtoo_dependencies' failed
make: *** [artifacts/.rmtoo_dependencies] Error 1
```
Is this the expected behavior of the development version? I use Python 2.7.9 on Debian unstable.

**Comment by florath** [comment]
Hello!

Yes - this is the expected behavior of the development version.
Please use the latest release if you want to use rmtoo.
(The master branch is stuck in the middle of a refactoring.)

Kind regards - Andre
