### ISSUE TITLE
Exception when installing using pip - Python 3.6.0

### ISSUE THREAD

**Issue by arthurspa** [florath/rmtoo#12]
I've got an exception when installing using pip in a virtualenv with python 3.6.0 (in Windows 7).

Python version (in venv):
```
arthur.s@MODEL-ARTHURS MINGW32 /d/Dev/temp/rmtoo
$ python --version
Python 3.6.0
(venv)
```

Trace:
```
arthur.s@MODEL-ARTHURS MINGW32 /d/Dev/temp/rmtoo
$ pip install rmtoo
Collecting rmtoo
  Using cached rmtoo-24.3.0-py2.py3-none-any.whl
Collecting odfpy==1.3.4 (from rmtoo)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x048F9F70>: Failed to establish a new connection: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied',)': /simple/odfpy/
Operation cancelled by user
(venv)
arthur.s@MODEL-ARTHURS MINGW32 /d/Dev/temp/rmtoo
$ pip install rmtoo
Collecting rmtoo
  Using cached rmtoo-24.3.0-py2.py3-none-any.whl
Collecting gitdb==0.6.4 (from rmtoo)
  Using cached gitdb-0.6.4.tar.gz
Collecting six>=1.10.0 (from rmtoo)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting stevedore>=1.21 (from rmtoo)
  Using cached stevedore-1.25.0-py2.py3-none-any.whl
Collecting numpy>=1.12.0 (from rmtoo)
  Using cached numpy-1.13.1-cp36-none-win32.whl
Collecting pylint>=1.7.1 (from rmtoo)
  Using cached pylint-1.7.2-py2.py3-none-any.whl
Collecting pyyaml>=3.12 (from rmtoo)
  Using cached PyYAML-3.12.tar.gz
Collecting future>=0.16.0 (from rmtoo)
  Using cached future-0.16.0.tar.gz
Collecting odfpy==1.3.4 (from rmtoo)
  Using cached odfpy-1.3.4.tar.gz
Collecting scipy>=0.19.0 (from rmtoo)
  Using cached scipy-0.19.1.tar.gz
    Complete output from command python setup.py egg_info:
    non-existing path in 'numpy\\distutils': 'site.cfg'
    Running from numpy source directory.
    C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\setup.py:367: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\system_info.py:572: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\system_info.py:572: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
    C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\setup.py", line 392, in <module>
        # higher up in this file.
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\setup.py", line 384, in setup_package
        if "--force" in sys.argv:
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\core.py", line 169, in setup
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\command\bdist_egg.py", line 152, in run
        self.run_command("egg_info")
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\egg_info.py", line 26, in run
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\build_src.py", line 148, in run
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\build_src.py", line 159, in build_sources
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\build_src.py", line 294, in build_library_sources
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\build_src.py", line 377, in generate_sources
      File "numpy\core\setup.py", line 672, in get_mathlib_info
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\command\config.py", line 243, in try_link
        self._check_compiler()
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\config.py", line 39, in _check_compiler
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\command\config.py", line 98, in _check_compiler
        dry_run=self.dry_run, force=1)
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\ccompiler.py", line 733, in new_compiler
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\mingw32ccompiler.py", line 69, in __init__
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\cygwinccompiler.py", line 126, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\arthur.s\AppData\Local\Temp\pip-build-fsy2ggyw\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\arthur.s\AppData\Local\Temp\pip-build-fsy2ggyw\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
        return installer(requirement)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\command\easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\command\easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\command\easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 251, in run_setup
        raise
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\setup.py", line 392, in <module>
        # higher up in this file.
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\setup.py", line 384, in setup_package
        if "--force" in sys.argv:
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\core.py", line 169, in setup
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\dev\temp\rmtoo\venv\lib\site-packages\setuptools\command\bdist_egg.py", line 152, in run
        self.run_command("egg_info")
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\egg_info.py", line 26, in run
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\build_src.py", line 148, in run
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\build_src.py", line 159, in build_sources
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\build_src.py", line 294, in build_library_sources
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\build_src.py", line 377, in generate_sources
      File "numpy\core\setup.py", line 672, in get_mathlib_info
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\command\config.py", line 243, in try_link
        self._check_compiler()
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\command\config.py", line 39, in _check_compiler
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\command\config.py", line 98, in _check_compiler
        dry_run=self.dry_run, force=1)
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\ccompiler.py", line 733, in new_compiler
      File "C:\Users\arthur.s\AppData\Local\Temp\easy_install-cn1ki2ju\numpy-1.13.1\numpy\distutils\mingw32ccompiler.py", line 69, in __init__
      File "c:\users\arthur.s\appdata\local\programs\python\python36-32\Lib\distutils\cygwinccompiler.py", line 126, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\arthur.s\AppData\Local\Temp\pip-build-fsy2ggyw\scipy\
(venv)
```

**Comment by arthurspa** [comment]
I've tried running
```
 pip install --only-binary=scipy scipy
Collecting scipy
  Could not find a version that satisfies the requirement scipy (from versions: )
No matching distribution found for scipy
```

**Comment by florath** [comment]
Thanks for reporting this.

Please note that rmtoo is currently not supported under Windows - and it is known that there are problems installing numpy and scipy. Please have a look at the dedicated Readme for Windows:
https://github.com/florath/rmtoo/blob/master/Readme-Windows.txt

scipy and numpy are only needed for the statistics module. Therefore theoretical it is possible to run rmtoo without scipy - when you do not need the appropriate rmtoo output modules.  But this will need some tweeking....

Maybe the easiest way is to use either a local Linux VM or a one preinstalled that is available in AWS EC2.
https://github.com/florath/rmtoo/tree/master/contrib/vmsetup

**Comment by florath** [comment]
I'll close this:

1. No input / change for month.
2. Report based on a unsupported OS.
