### ISSUE TITLE
make: *** [.rmtoo_dependencies] Error 1

### ISSUE THREAD

**Issue by hhanff** [florath/rmtoo#13]
Hi!

I wanted to give rmtoo a try on Ubuntu 14.04.5 LTS but I cannot get it running.
I followed the pip instruction routine described [here](https://pypi.python.org/pypi/rmtoo#installation-using-virtualenv-pip)

Running ```make``` throws the following error:

```
(venv)[MyNewProject] make RMTOO_CONFIG=Config.json
Makefile:32: .rmtoo_dependencies: No such file or directory
rmtoo -j file://Config.json \
		--create-makefile-dependencies=.rmtoo_dependencies
Traceback (most recent call last):
  File "/home/hhanff/Projekte/rmtoo/RMTOO/venv/bin/rmtoo", line 11, in <module>
    sys.exit(main())
  File "/home/hhanff/Projekte/rmtoo/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 89, in main
    main_impl(sys.argv[1:], sys.stdout, sys.stderr)
  File "/home/hhanff/Projekte/rmtoo/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 81, in main_impl
    exitfun(not mainfunc(args, mstdout, mstderr))
  File "/home/hhanff/Projekte/rmtoo/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 72, in main_func
    config, input_mods = MainHelper.main_setup(args, mstdout, mstderr)
  File "/home/hhanff/Projekte/rmtoo/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/main/MainHelper.py", line 37, in main_setup
    config = MainHelper.main_setup_config(args)
  File "/home/hhanff/Projekte/rmtoo/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/main/MainHelper.py", line 30, in main_setup_config
    config.merge_cmd_line_params(args)
  File "/home/hhanff/Projekte/rmtoo/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/configuration/Cfg.py", line 170, in merge_cmd_line_params
    ldicts = CmdLineParams.create_dicts(args)
  File "/home/hhanff/Projekte/rmtoo/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/configuration/CmdLineParams.py", line 123, in create_dicts
    lresult.append(CmdLineParams.add_args(args))
  File "/home/hhanff/Projekte/rmtoo/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/configuration/CmdLineParams.py", line 109, in add_args
    if args is None or args == []:
  File "/usr/lib/python2.7/argparse.py", line 1160, in __eq__
    return vars(self) == vars(other)
TypeError: vars() argument must have __dict__ attribute
make: *** [.rmtoo_dependencies] Error 1

```

```
# python --version
Python 2.7.6

```

Can you help?

**Comment by hhanff** [comment]
Same on my laptop:

```
(venv)[hhanff@hhanff-l][MyNewProject] make RMTOO_CONFIG=Config.json
Makefile:32: .rmtoo_dependencies: No such file or directory
rmtoo -j file://Config.json \
		--create-makefile-dependencies=.rmtoo_dependencies
Traceback (most recent call last):
  File "/tmp/RMTOO/venv/bin/rmtoo", line 11, in <module>
    sys.exit(main())
  File "/tmp/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 89, in main
    main_impl(sys.argv[1:], sys.stdout, sys.stderr)
  File "/tmp/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 81, in main_impl
    exitfun(not mainfunc(args, mstdout, mstderr))
  File "/tmp/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 72, in main_func
    config, input_mods = MainHelper.main_setup(args, mstdout, mstderr)
  File "/tmp/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/main/MainHelper.py", line 37, in main_setup
    config = MainHelper.main_setup_config(args)
  File "/tmp/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/main/MainHelper.py", line 30, in main_setup_config
    config.merge_cmd_line_params(args)
  File "/tmp/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/configuration/Cfg.py", line 170, in merge_cmd_line_params
    ldicts = CmdLineParams.create_dicts(args)
  File "/tmp/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/configuration/CmdLineParams.py", line 123, in create_dicts
    lresult.append(CmdLineParams.add_args(args))
  File "/tmp/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/configuration/CmdLineParams.py", line 109, in add_args
    if args is None or args == []:
  File "/usr/lib/python2.7/argparse.py", line 1160, in __eq__
    return vars(self) == vars(other)
TypeError: vars() argument must have __dict__ attribute
make: *** [.rmtoo_dependencies] Error 1
```

**Comment by florath** [comment]
I'm sorry - but I have no idea.

Looking into the argparse module I did not find any hint.

How did you install your python? AFAIK the version that comes with Ubuntu 14.04 is 2.7.5 (https://packages.ubuntu.com/trusty/python).

Do you have any chance to update to a somewhat newer version of python?

I just tested it here using python 2.7.13 and had no problems.

**Comment by hhanff** [comment]
I will try it on Ubuntu 16.04 in the following days.

**Comment by hhanff** [comment]
All right. The problem also occured on 16.04. In the end I moved my .bashrc and the problem vanished. It compiles now.

If I find the time to further investigate the problem I will let you know. Thanks for your support.

**Comment by hhanff** [comment]
Found this

```
export PYTHONPATH="$PYTHONPATH:$HOME/.python"
```
in my .bashrc which caused the error.
