### ISSUE TITLE
Exception when run from virtualenv

### ISSUE THREAD

**Issue by joesteeve** [florath/rmtoo#3]
``` shell
Traceback (most recent call last):
  File "/home/joe/work/projects/HiPro/fs-work/rmtoo/venv/bin/rmtoo", line 14, in <module>
    main(sys.argv[1:], sys.stdout, sys.stderr)
  File "/home/joe/work/projects/HiPro/fs-work/rmtoo/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 76, in main
    exitfun(not main_func(args, mstdout, mstderr))
  File "/home/joe/work/projects/HiPro/fs-work/rmtoo/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 68, in main_impl
    config, input_mods = MainHelper.main_setup(args, mstdout, mstderr)
  File "/home/joe/work/projects/HiPro/fs-work/rmtoo/venv/local/lib/python2.7/site-packages/rmtoo/lib/main/MainHelper.py", line 40, in main_setup
    mods = InputModules(moddirs[0], config)
  File "/home/joe/work/projects/HiPro/fs-work/rmtoo/venv/local/lib/python2.7/site-packages/rmtoo/lib/InputModules.py", line 70, in __init__
    self.__load(dir_components, mod_components)
  File "/home/joe/work/projects/HiPro/fs-work/rmtoo/venv/local/lib/python2.7/site-packages/rmtoo/lib/InputModules.py", line 75, in __load
    for filename in sorted(os.listdir(os.path.join(*dir_components))):
OSError: [Errno 2] No such file or directory: '/usr/share/pyshared/rmtoo/inputs'
```

**Comment by joesteeve** [comment]
'distutils' should be used to fetch the module directory.
